### PR TITLE
doc fixes, chiefly the class name correction, hopefully a little clea…

### PR DESCRIPTION
**Pull request by clintonroy**
…rer english.

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: thanks!  Going to let CI spin before merging (just to be safe).

**Comment by klauer** [comment]
Some overlap with the (for whatever reason) yet-to-be-merged doc fixup PR: https://github.com/NSLS-II/ophyd/pull/617/files#diff-537b59c647f39fcb2087ba8ec729c5e5R303

**Comment by clintonroy** [comment]
ugh, my bad for not looking at other PRs, happy to wait till that big one is merged and do my tweaks on top of that.

**Comment by klauer** [comment]
Thanks, @clintonroy! The other PR is in, so if you still have the inspiration to help with the documentation, by all means go ahead. 😉

**Pull request closed without merging**
