### PR TITLE
MNT: hook for filestore mixin make_filename

### PR DESCRIPTION
**Pull request by klauer**
Need to be able to:

1. Modify the filenames being saved through FileStoreBase (NFS+PIMS choke with hundreds of thousands of files in one directory)
2. Create the directory and set permissions

With this small change, I can do both in my subclass. For (1) I'm making a subdirectory with the start of the filename uid since I don't have access to any scan information during `stage()`.

P.S. @danielballan here's an opportunity to disagree!

### CODE REVIEW

**Comment by tacaswell** [comment]
Is there an obvious way to inject information (like the runstart uid) into stage?  One way would be a `configure` message to the AD before the `stage`?  Another would be to start allowing stage to take arguments.

**Comment by tacaswell** [comment]
Other wise :+1:

**Comment by klauer** [comment]
I do other per-run configuration-related things in detector `set` methods. That's the only place in the current design it'll go as far as I can tell.

**Comment by tacaswell** [comment]
I think you should be doing that through `configure`, if you `set` a detector in the middle of a run you can make the descriptor lie about it's settings.

**Comment by klauer** [comment]
Well, (`un`)`stage` used to be (`de`)`configure`, so `set` was the only option... I suppose you're correct post-refactor - my old `set` should become `configure`.

**Comment by tacaswell** [comment]
Ah, sorry I lost track of which version of ophyd you ar eworking against.

**Pull request merged**
