### PR TITLE
Ad queue draining

### PR DESCRIPTION
**Pull request by tacaswell**
This is no way ready to merge yet and I will rebase / squash / force-push at will.

The end goals of this work are:

 1. be sure there are no images in the processing pipelines we care about when.
 2. enable running collection with blocking callbacks disabled.
 3. lay ground work for sophisticated 'modes' management of AD devices.

### CODE REVIEW

**Comment by danielballan** [comment]
@tacaswell Safe to close this now, given fixes to AD?

**Comment by tacaswell** [comment]
I think we will eventually want to salvage most of this (for example, only caring about plugins that are enabled when walking the processing tree).

Having this for old versions of AD is also not a bad thing.

**Comment by klauer** [comment]
@tacaswell do you have details on what's left to fix/salvage from this?

**Comment by tacaswell** [comment]
I think that this can be abandoned due to the changes Mark put into 3.3 for us.

**Pull request closed without merging**
