### PR TITLE
ENH/TST: Define OphydObj.__contains__

### PR DESCRIPTION
**Pull request by danielballan**
This is just to generate useful discussion around https://github.com/NSLS-II/wishlist/issues/108. I wanted something to concrete to look at.

### CODE REVIEW

**Comment by danielballan** [comment]
Then bluesky plans would do something like:

```python
# objs_read is a list of objs we have read so far in this Event bundle
# obj is an object we are about to read

for obj_read in objs_read:
    if obj in obj_read or obj_read in obj:
         # redundnat -- cut out
# carry on
```

**Comment by tacaswell** [comment]
Signals also need an always false `__contains__`

**Comment by danielballan** [comment]
Haha, did we skip the discussion and jump right to performance optimizations? Are you :+1: on this API?

**Comment by tacaswell** [comment]
It isn't a performance optimization, signal can go in the detector list so bluesky will be checking `obj in signal` which will fail.

I do not see how this as 'policy', this is the hardware abstraction knowing enough about it's self to allow the code that implements 'policy' to do so.  Knowing if two python objects are part of the same `Device` seems pretty fundamental to the abstraction.

`common_ancestor` still seems independently useful but not immediately needed.

**Comment by danielballan** [comment]
> It isn't a performance optimization, signal can go in the detector list so bluesky will be checking obj in signal which will fail.

Why would it fail? I believe it's even covered by a test in the original commit. Note that this is on OphydObj (superclass of both Device and Signal) not Device itself.

**Comment by danielballan** [comment]
> common_ancestor still seems independently useful but not immediately needed.

Is this different that `obj.root == other.root`? Were you thinking that `common_ancestor` returned the ancestor itself, not a boolean?

**Comment by tacaswell** [comment]
@danielballan Ah, I missed where it went (thought this was on `Device`) nvm :sheep: 

Yes,  `common_ancestor` should return the first common ancestor

```python

a.b.c.common_ancestor(a.b.d) is a.b

```

**Comment by danielballan** [comment]
I agree that we will very likely want a method like that as well. I have added it, with tests, in a separate commit. OK with this, @dchabot, @klauer?

**Comment by klauer** [comment]
Sorry for the late input...

I'm not a fan of adding on `__contains__` to `Device`. It seems to indicate that we should also have `__getitem__`/etc defined. It also seems to me that it should be more of `'attribute_name' in device` versus `obj in device`-style checks...

For whatever reason, it seems less ugly to me to define `Device.__iter__` such that you can walk through its immediate children -- sub-devices and signals. From there, a simple (external) utility function could generate a whole tree without poking into any `Device` internals.

Come to think of it, all of these functions (`root` included) could/should have been implemented outside of the device itself...

**Comment by danielballan** [comment]
> I'm not a fan of adding on __contains__ to Device. It seems to indicate that we should also have __getitem__/etc defined. 

I disagree that `__contains__` and `__getitem__` (etc.) go hand in hand. I think supporting `in` gives users a terse and expressive way of testing the hierarchy. I do agree your feeling that we should avoid an exploding litany of convenience methods and generally leave graph exploration to external code.

>  It also seems to me that it should be more of 'attribute_name' in device versus obj in device-style checks...

We *sort of* already have this: `other.name in self.signal_names` would accomplish this with strings. I guess the point of adding `in` is to avoid exposing `signal_names` as another specially-named piece of API. Python provides `__contains__`, and `signal_names` is sort of reinventing that.

**Comment by klauer** [comment]
> I do agree your feeling that we should avoid an exploding litany of convenience methods and generally leave graph exploration to external code.

If that's the case, then we still have to define what's the minimal amount of things to leave on `Device` so that tree traversal/relationship-determination can be done with external utility functions. From a high-level standpoint, `parent` and `children` are the only things that are strictly necessary. I suppose it's too late to remove `root`, so we can leave it in. The only question is how to expose `children`, then.

> We sort of already have this: other.name in self.signal_names would accomplish this with strings. I guess the point of adding in is to avoid exposing signal_names as another specially-named piece of API. Python provides __contains__, and signal_names is sort of reinventing that.

In hindsight, leaving `signal_names` public that was probably a mistake (beside for its name). We probably should've used `__contains__`, `__iter__`, etc. Oh well.

**Comment by danielballan** [comment]
Actually, `signal_names`is not public in the sense of being used by downstream (bluesky). It could be deprecated/made private/left undocumented. Do we agree that `__iter__` would iterate over the subdevices/signals in order? That  would give us `__contains__` for free. The rest of the traversal could be handled by external functions if you prefer.

**Comment by klauer** [comment]
I think so (on all accounts), but perhaps we should wait until Monday to act on this.

**Comment by danielballan** [comment]
Agreed. I'm underwater with beamline support today. To be continued.

**Comment by danielballan** [comment]
It still seems like `__iter__` and/or `__contains__` would be useful to add, but there is no immediate need in light of https://github.com/NSLS-II/bluesky/pull/382

**Comment by klauer** [comment]
We definitely could use some more options to introspect `Device`s. One of my main desires to allow such hierarchy traversal at the class-level (i.e., `@classmethod`s) without poking into private attributes (or requiring signal instantiation). Those methods could then be used at the instance level as well. More on that some other time.

**Pull request closed without merging**
