### PR TITLE
Fix ophyd readout

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
This super-cedes gh-107.

@danielballan @ericdill This should be merged so that we can re-deploy to HXN and roll this out to the rest of the beam lines tomorrow.

**Comment by danielballan** [comment]
Looks good. Thanks for slogging through this one today.

**Comment by danielballan** [comment]
I leave it to @ericdill to merge. @tacasell I suggest tagging an rc.

**Comment by ericdill** [comment]
Why do you want me to merge this?  I don't know enough about this part of ophyd to have any opinions on the matter. @stuwilkins or @dchabot should be the ones providing feedback here

**Comment by danielballan** [comment]
I think your merge commits are affected.

**Pull request merged**
