### PR TITLE
CI: Use epics-on-travis instead of conda or Debian.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by danielballan** [comment]
Travis did not pick this up....

**Comment by mrakitin** [comment]
What's the motivation?

**Comment by tacaswell** [comment]
Bit more reliable / controlled and faster to install.

**Comment by klauer** [comment]
Travis does _not_ like these changes or this PR for whatever reason.

**Comment by klauer** [comment]
Let's just move to azure eventually...

**Pull request closed without merging**
