### PR TITLE
first test travis

### PR DESCRIPTION
**Pull request by jrmlhermitte**
Don't merge. We will add strict dependence on networkx 2.0.

First, I have added `conda list` so we know what we're running on travis.

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
for issue #428 
ready to merge

**Comment by tacaswell** [comment]
I am ok with merging this, but if we currently don't use any API that is not supported by both, why pin the version?

**Comment by jrmlhermitte** [comment]
This is my misunderstanding from #428. I thought we'd just switch to 2.0.

If we don't, should we keep testing for both versions, so that we're aware of it the day it breaks?
Doing so could be tricky if any dependent library requires 2.0.

I'd vote we don't merge this, and don't add a test for 2.0. Does that sound fair?

**Comment by tacaswell** [comment]
@jrmlhermitte Please open PRs from your fork rather than working on upstream branches.

**Comment by klauer** [comment]
Now that there are many 1000s of commits following the standard pattern of "TAG: message", why are PRs being merged that do not follow this format?

**Comment by jrmlhermitte** [comment]
thanks. ill use my branch from now on.
thanks @klauer for the feedback. will try to follow the convention

**Pull request merged**
