### PR TITLE
Immutable component names

### LINKED ISSUE #581: component_names should be immutable
should things like `pilatus2M.component_names.remove("trans1")`  be possible etc?

@danielballan

### PR DESCRIPTION
**Pull request by tacaswell**
Closes #581.

### CODE REVIEW

**Comment by mrakitin** [comment]
Should the description be changes in the [docs](https://github.com/NSLS-II/ophyd/blob/6877e1c70a582049eca9fef7518bf853a994c03c/doc/source/device-overview.rst#classdevice) too? In particular:
```
:attr:`component_names` | List of the names components on this device. Direct children only
```

**Comment by danielballan** [comment]
I take that usage of "List" to be the English word not the Python data structure. I think it's probably more readable/accessible that `tuple`, and the distinction is not important in that context.

**Comment by tacaswell** [comment]
@danielballan then failures look like caproto bugs....

**Comment by danielballan** [comment]
@tacaswell Good catch. Opened issue: https://github.com/NSLS-II/caproto/issues/328

**Comment by mrakitin** [comment]
OK, that's clear, thanks @danielballan. Yes, I also noticed the consistently failing tests. Great the issue is uncovered!

**Pull request merged**
