### PR TITLE
ENH: Add sumAll to QuadEM

### PR DESCRIPTION
**Pull request by jrmlhermitte**
From #527

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
Good question. I assumed this was a typo because I didn't see sumAll. I'll ask Lin to double check.
[Here](https://github.com/NSLS-II-LIX/profile_collection/blob/master/startup/20-bpm.py#L34) is the usage.

**Comment by mrakitin** [comment]
I see, thanks. The tests are still failing, probably `read_attrs` of `FakeQuadEM` should be updated with `sumAll`.

**Comment by jrmlhermitte** [comment]
Lin confirmed that it should be sumAll and he likely made a mistake.
ill check soon, thanks!

**Comment by jrmlhermitte** [comment]
I think we have to override the `FakeQuamEM` with a fake version of `sumAll`. waiting on Travis...

**Comment by tacaswell** [comment]
You probably need to make our fake QuadEM smarter to get the tests to pass.

**Comment by jrmlhermitte** [comment]
passes now but py3.6 fails:
```

E           TimeoutError: Server at ('172.17.0.2', 5064) did not respond to attempt to read channel named 'XF:31IDA-OP{Tbl-Ax:X1}Mtr.VAL' within 1.9999873499999694-second timeout.
```

I think this is unrelated. Is this good to go?

**Comment by jrmlhermitte** [comment]
thanks @tacaswell !

**Pull request merged**
