### PR TITLE
ENH : Added quotes for __str__ method on EpicsMotor

### PR DESCRIPTION
**Pull request by stuwilkins**
Added quotes round string in __str__ method so this can be used to create the object.

### CODE REVIEW

**Comment by stuwilkins** [comment]
I just found something else which I think comes from pyepics. The EpicsSignal comes back as:

<pre>
EpicsSignal(value=296.68, read_pv=<PV 'XF:23ID1-ES{TCtrl:1-Chan:A}T-I', count=1, type=time_double, access=read/write>, write_pv=None)
</pre>

the <PV ...> is not a real repr. should we subclass PV from pyepics and overwrite that?

**Comment by stuwilkins** [comment]
Sorry problem with html parsing

`EpicsSignal(value=296.68, read_pv=<PV 'XF:23ID1-ES{TCtrl:1-Chan:A}T-I', count=1, type=time_double, access=read/write>, write_pv=None)`

**Comment by klauer** [comment]
We could subclass it, or just change `epics.PV._fmtsca` (scalar format) and `_fmtarr` (array format) on library initialization. I assume your preference would be something like `PV(pvname='XF:23ID1-ES{TCtrl:1-Chan:A}T-I', ...)`? 

To be fair, our `repr`s aren't correct either since we can't recreate the object from the string. 

My issue with doing it properly is that real `repr`s can get terribly verbose and not show what you would really want as an ophyd user. Say you have an EpicsSignal, `sig`, and type just that in IPython session, you'll see its `repr`, unless you force it into a string. A proper `repr` implementation would only show the PV names that it uses, while `str` would show whatever information we deem useful (value, etc.). The real question is then: does the utility of recreating objects from `repr` strings outweigh this?

**Comment by stuwilkins** [comment]
Hi Ken,

yes my preference would be `PV(pvname = …)` for the `__repr__`.

I though that if you have a `__str__` method then that is shown when the user prints or even just types it in IPython. So we can have verbose `__repr__` strings and nice `__str__` strings


S


On Jan 6, 2015, at 10:22 AM, K Lauer <notifications@github.com<mailto:notifications@github.com>> wrote:


We could subclass it, or just change epics.PV._fmtsca (scalar format) and _fmtarr (array format) on library initialization. I assume your preference would be something like PV(pvname='XF:23ID1-ES{TCtrl:1-Chan:A}T-I', ...)?

To be fair, our reprs aren't correct either since we can't recreate the object from the string.

My issue with doing it properly is that real reprs can get terribly verbose and not show what you would really want as an ophyd user. Say you have an EpicsSignal, sig, and type just that in IPython session, you'll see its repr, unless you force it into a string. A proper repr implementation would only show the PV names that it uses, while str would show whatever information we deem useful (value, etc.). The real question is then: does the utility of recreating objects from repr strings outweigh this?

**Comment by klauer** [comment]
If we can find another reason to subclass `epics.PV`, let's go that route. As it is, I think just replacing those strings should suffice.

A quick check shows IPython and Python behave similarly with `repr`/`str`:

```python
In [1]: class A(object):
   ...:     def __repr__(self): return 'repr'
   ...:     def __str__(self): return 'str'
   ...:

In [2]: a = A()

In [3]: a
Out[3]: repr

In [4]: str(a)
Out[4]: 'str'
```

**Comment by stuwilkins** [comment]
Mmm that is unfortunate it would be much better if the __str__ was returned at the ipython prompt. Do I have the understanding of `__str__` and `__repr__` backwards?

Perhaps we should just put in the `__repr__` for the PV the actual name as PV(‘pv_name’).

S

On Jan 6, 2015, at 10:42 AM, K Lauer <notifications@github.com<mailto:notifications@github.com>> wrote:


If we can find another reason to subclass epics.PV, let's go that route. As it is, I think just replacing those strings should suffice.

A quick check shows IPython and Python behave similarly with repr/str:

In [1]: class A(object):
   ...:     def __repr__(self): return 'repr'
   ...:     def __str__(self): return 'str'
   ...:

In [2]: a = A()

In [3]: a
Out[3]: repr

In [4]: str(a)
Out[4]: 'str'

**Comment by klauer** [comment]
> Please do not pollute the object model by subclassing from pyepics classes. I still think composition is the right approach here…

No argument there.

> Mmm that is unfortunate it would be much better if the __str__ was returned at the ipython prompt. Do I have the understanding of `__str__` and `__repr__` backwards?

Check [here](https://docs.python.org/2/reference/datamodel.html#object.__repr__) and maybe even [here](http://satyajit.ranjeev.in/2012/03/14/python-repr-str.html)

**Comment by tacaswell** [comment]
attn @danielballan regarding IPython display hooks.

**Pull request merged**
