### PR TITLE
Fix fake PV

### LINKED ISSUE #477: FakeEpicsPV Callbacks
I am currently in the process of migrating SLAC's devices for compatibility with latest (we had previously frozen the version for a bit while we worked on other things). I'm having trouble migrating our unit tests, which previously used a modified version of `FakeEpicsPV` but now include the class from ophyd's `test/conftest.py` due to all the changes with the `control_layer`.

My issue is that the class's callbacks are stored in `WeakValueDictionary`:

https://github.com/NSLS-II/ophyd/blob/master/ophyd/tests/conftest.py#L51-L54

Keeping this as a `WeakValueDictionary`, all of my callbacks are being instantly garbage collected, so I can't write unit tests for things like returning a working `Status` object after a `set` call if they depend on an EPICS subscription.

My questions are:
1. What is the purpose of using a `WeakValueDictionary` here?
2. What are the negative consequences of changing this to a normal `dict` object? (my tests and the ophyd tests pass with this change)
3. If there are consequences, do I need to handle this by keeping a reference to every callback in all of my device implementations?

### PR DESCRIPTION
**Pull request by tacaswell**
I sneaked in some style and warning changes as well.

closes #477

### CODE REVIEW

**Comment by tacaswell** [comment]
@teddyrendahl I think you have merge power ;)

**Comment by teddyrendahl** [comment]
Thoughts on eliminating the lock in the `.put` method per https://github.com/NSLS-II/ophyd/issues/477#issuecomment-341784217?
https://github.com/NSLS-II/ophyd/blob/d63d22789dbbf6fad36312008df982e267b190c7/ophyd/tests/conftest.py#L209-L214

**Comment by tacaswell** [comment]
Eliminating locks that cause deadlocks is usually not the right solution as the deadlock is telling you here is a race condition that needs to be ironed out.

**Comment by danielballan** [comment]
@ZLLentz @teddyrendahl If you think this is worth merging as is into 1.0.0 (final), which I plan to tag late in the day on Monday, please merge.

It seems like we should take our time ironing out the deadlock / race condition carefully. We'll be tagging a bug-fix release in 2-3 weeks anyway, so the stakes are low.

**Pull request merged**
