### PR TITLE
WIP [do not merge] HKL support

### PR DESCRIPTION
**Pull request by klauer**
Work-in-progress

* Needs plenty of cleaning up
* Some modifications to examples (they were completely broken after the namespace flattening/moving around)
* As of writing, only `examples/hkl_test.py` has been updated and is 'working' (i.e., not crashing)
* Need to update notebooks

See https://github.com/NSLS-II/conda-prescriptions/pull/94 for my PR with all the conda packages necessary to install the hkl library. I only have pre-built packages for linux-x86_64 (HKL library will not build on OSX) and Python 3.4 currently on my [anaconda.org](https://anaconda.org/klauer/hkl/files) channel.

### CODE REVIEW

**Comment by klauer** [comment]
Updated to include axis name remapping from @dchabot.

The branch itself may need a small amount of work with `FakePositioner` in the examples with the impending positioner refactor.

**Comment by danielballan** [comment]
What is the status of this? Was some version of hkl used at CSX recently?

**Comment by klauer** [comment]
Closing in favor of https://github.com/dchabot/hklpy

**Comment by cmazzoli** [comment]
Apologies Ken, I am a little new to the terminology you use here.. What do
you mean?
Could we please test Daron's idea together?
Please let me know.
Claudio

**Comment by klauer** [comment]
@cmazzoli: @dchabot moved hkl support into its own package, which is now available under the NSLS-II github organization [here](https://github.com/NSLS-II/hklpy).

Regarding your specific issue, perhaps it'd be best if the three of us could meet before @dchabot leaves so he can fill me in on the progress you and he have made with the integration. From there, we can poke around and try to diagnose it further.

**Pull request closed without merging**
