### PR TITLE
Mds related fixes

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @dchabot @stuwilkins 

How can I test this with out a beamline?

**Comment by stuwilkins** [comment]
Tom, I have just finished a test stand at CSX with test motors and detectors.
Can we have a second instance of mongo setup? Perhaps If i put that on xf23id1-ioc2 then we could have a complete place to test everything.

S
On Feb 15, 2015, at 12:49 AM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


attn @dchabot<https://github.com/dchabot> @stuwilkins<https://github.com/stuwilkins>

How can I test this with out a beamline?

**Comment by ericdill** [comment]
Do you want me to install mongo on ioc2?

**Comment by stuwilkins** [comment]
Done.


On Feb 15, 2015, at 8:40 AM, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you want me to install mongo on ioc2?

**Pull request merged**
