### PR TITLE
MNT: make log_pos friendlier

### PR DESCRIPTION
**Pull request by tacaswell**
closes a bug report

### CODE REVIEW

**Comment by klauer** [comment]
:+1: though it would probably be good to add `RuntimeError` to the docstring "Raises" section.
CI probably doesn't even smoke test this...

**Comment by tacaswell** [comment]
the original issue was https://github.com/NSLS-II/Bug-Reports/issues/110 where they were confused why this was silently passing.

**Comment by tacaswell** [comment]
Turns out it does test it. Adding a real test is on the to do list.

**Comment by klauer** [comment]
Smoke test is failing due to the new exception being raised when a logbook isn't set

**Comment by danielballan** [comment]
bump @tacaswell

**Comment by danielballan** [comment]
The mechanism this was trying to fix has been removed.

**Comment by ambarb** [comment]
Does this mean that `from ophyd import log_pos` will not work now?

**Comment by ambarb** [comment]
Does this mean we can no longer `import log_pos from ophyd`?

https://github.com/NSLS-II/ophyd/search?utf8=%E2%9C%93&q=log_pos&type=

**Comment by ambarb** [comment]
nevermind.  I see now that we were using
`from pyOlog.ophyd_tools import *`  which is local.

**Pull request closed without merging**
