### PR TITLE
Turn on/off file plugin after before/scan

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by danielballan** [comment]
@klauer Will this cause you any trouble?

**Comment by ericdill** [comment]
closes https://github.com/NSLS-II/ophyd/issues/133

**Comment by klauer** [comment]
Probably not. You might have seen from some of my recent changes to the area_detector module that I like the ability to at least toggle functionality like this.

Sometimes non-optional features/settings/whatever are buried so deeply into the class hierarchy you have no choice but to re-implement everything surrounding it just to skip it in your subclass.

**Comment by ericdill** [comment]
This needs to go in before the deployment to CHX

**Comment by danielballan** [comment]
@klauer Yeah I agree that's a major flaw with the current design. I think we can do better in the medium term.

**Comment by ericdill** [comment]
@danielballan should this go in before too much longer?

**Comment by danielballan** [comment]
Merged so that we don't break CSX. A more customizable AreaDetector is high on the to-do list, but it's not going to make the cutoff for September 30.

**Pull request merged**
