### PR TITLE
Enh pseudo lock

### PR DESCRIPTION
**Pull request by danielballan**
#358 rebased on master (with #353 now merged)

### CODE REVIEW

**Comment by danielballan** [comment]
I would like to source-install this somewhere and try it out on a pseudopos before we roll out everywhere.

**Comment by tacaswell** [comment]
Does @NSLS-II/csx volunteer?

**Comment by ambarb** [comment]
If okay with Claudio, we can do it today (thought we both are busy 2:45 - 3:45.  Otherwise, you can install it remotely on Friday, but we will not be able to test it until the facilities work is complete in the user area (probably Tuesday of next week).

**Comment by danielballan** [comment]
If you two can figure out how to source install that branch of ophyd, go for it. If you need help it will have to wait for next week.

**Comment by danielballan** [comment]
Merging (these commits are Ken's, not mine)

**Pull request merged**
