### PR TITLE
FIX: add data_counter when saving datum

### PR DESCRIPTION
**Pull request by licode**
add data_counter in datum and corresponding output numpy filenames. test to be added.

### CODE REVIEW

**Comment by licode** [comment]
just added.

**Comment by klauer** [comment]
Tried out github's conflict resolver - looks like it just creates a merge commit. You may consider rebasing and force pushing to clean it, @licode.

**Comment by licode** [comment]
Thanks for quickly resolving this. I was about to rebase. connection time is longer than 1sec limit.

**Comment by klauer** [comment]
Rebased, force-pushed, and relevant tests confirmed working. Merging.
Thanks @licode!

**Pull request merged**
