### PR TITLE
Fastccd multigain

### PR DESCRIPTION
**Pull request by tacaswell**
@klauer @dchabot @stuwilkins

### CODE REVIEW

**Comment by danielballan** [comment]
attn @vivekthampy

**Comment by stuwilkins** [comment]
@klauer @dchabot @tacaswell 

I need to review this a bit as I haven't seen what @vivekthampy is doing in detail and how valid it is for what we need longterm CSX. I would appreciate @klauer  and @dchabot weighing on on the methodology here.

**Comment by tacaswell** [comment]
If you look at the first commit you can see exactly what @vivekthampy emailed.

**Comment by stuwilkins** [comment]
Thanks @tacaswell , The point is I would like @cmazzoli and @ambarb to weigh in on this and see if it is what the beam line needs and if it can be improved before we merge it in.

**Comment by klauer** [comment]
@stuwilkins There's a large amount of refactoring to be done in the near future with areaDetector stuff. Given that, if the changes in this PR work well enough for you now, it gets a thumbs up from me.

**Comment by tacaswell** [comment]
I do not think this has been tested on real hardware yet.

**Comment by stuwilkins** [comment]
Ok I will test with @ambarb and @cmazzoli and let you know how it works.

**Comment by tacaswell** [comment]
Any progress on this?

**Comment by tacaswell** [comment]
closes #152

**Comment by klauer** [comment]
No longer relevant with new ophyd version - closing.

**Comment by danielballan** [comment]
@vivekthampy Getting your functionality up and running at CSX is now very straightforward. Come see me when you when to get this done -- should be an hour's work, at most.

**Pull request closed without merging**
