### PR TITLE
pass path to sim so we can control where files are written

### PR DESCRIPTION
**Pull request by CJ-Wright**
This should help with pytest leakage (since python just puts the data anywhere)

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@NSLS-II/dama ready for review!

**Comment by danielballan** [comment]
Useful! Thank you.

**Comment by CJ-Wright** [comment]
There is a tandem PR in Bluesky

**Comment by danielballan** [comment]
‘hw’ is mostly

**Comment by CJ-Wright** [comment]
? Am I missing some connect?

**Comment by danielballan** [comment]
Sorry, this is the beginning of an old drafted comment. I must have bumped "Comment" on my phone by mistake. Not sure where I was going with this... I like the PR.

**Pull request merged**
