### PR TITLE
ENH/WIP: partially working Pixirad configuration

### PR DESCRIPTION
**Pull request by tacaswell**
attn @gjwillms 

This needs to be re-tested at SRX as we lost the working version due to upgrade thrashing.

### CODE REVIEW

**Comment by tacaswell** [comment]
Issue seems to be crossed imports.

**Comment by klauer** [comment]
`SignalRO` -> `EpicsSignalRO`
`Signal` -> `EpicsSignal`
?

**Comment by klauer** [comment]
There are stubbing utilities in ophyd to take in the areaDetector database files and generate these, FYI.

Does `cam.wait_for_connection(all_signals=True)` succeed? This is something one should verify prior to merging.

**Comment by tacaswell** [comment]
This is just dumping on to GH what garth sent me in an email.

**Pull request closed without merging**
