### PR TITLE
FIX: non-automonitored EpicsSignal timestamps

### PR DESCRIPTION
**Pull request by klauer**
Ref #274

### CODE REVIEW

**Comment by tacaswell** [comment]
Does this mean we can get into the state where we get the value from one epics 'update' (record processing? sorry, do not know the right terms of art) and then the timestamp from the next in a `read` call?

**Comment by klauer** [comment]
It would be the same if `automonitor` were enabled and a value update callback came inbetween a call to `get()` and `.timestamp` - it's not an atomic operation in either case.

**Comment by tacaswell** [comment]
fair enough.  I take it `pyepics` does not have an atomic operation for this?

**Comment by klauer** [comment]
If automonitored, `epics.PV` value and timestamp come back in the same C `struct` (assuming `form='time'`). However, as it requires two calls on the pyepics level (`get()` and `.timestamp`), therein lies the possibility for a mismatch.

If not automonitored, two `libca` calls are required (at least in the current implementation) to get the value then the timestamp (`get_timevars` at the `epics.PV` level). There's certainly more of a possibility for a mismatch in this case.

We should probably return to the case of automonitoring when timestamps matter - updating the internal state of `EpicsSignal` objects based on the callback data (as the timestamp/value will come bundled together). This would mean that `EpicsSignal.get()` would have to start replicating the logic of the various permutations of `epics.PV.get`'s keyword arguments.

**Comment by tacaswell** [comment]
:+1: 

This needs to get merged before tagging @danielballan

**Pull request merged**
