### PR TITLE
ENH: Derived signal

### PR DESCRIPTION
**Pull request by klauer**
The concept of a 'derived signal' with a value and description based on another.

Submitting to see what people think - not saying this has to go in or necessarily even should. 

As an example, I've used this in an ROI's low and high eV `Component`s, which calculate user-friendly eV units from bin numbers.:

```python
class EvSignal(DerivedSignal):
    '''A signal that converts a bin number into electron volts'''
    def __init__(self, parent_attr, *, parent=None, **kwargs):
        bin_signal = getattr(parent, parent_attr)
        super().__init__(derived_from=bin_signal, parent=parent, **kwargs)

    def get(self, **kwargs):
        bin_ = super().get(**kwargs)
        return bin_to_ev(bin_)

    def put(self, ev_value, **kwargs):
        bin_value = ev_to_bin(ev_value)
        return super().put(bin_value, **kwargs)

    def describe(self):
        desc = super().describe()
        desc[self.name]['units'] = 'eV'
        return desc
```
Note that this inherits from DerivedSignal and gets a component from its parent, so in a way this example is `DerivedFromSibling`, I suppose.

Pluses
* Stands out from other signals - `isinstance()` indicates it's a soft signal based on another one
* May save a couple lines of code here or there
* `describe` could do something special to indicate from where it was derived

Minuses
* How's it any different from just passing in the `Signal` and working with it in any other class?
* More classes = more confusion
* Discussion, blah

### CODE REVIEW

**Comment by danielballan** [comment]
I like this. I went back for it when you shared it with my over GChat but forget to say anything -- sorry. I think it is a useful concept to add.

**Comment by klauer** [comment]
Thanks @danielballan. Anyone else disagree (or feel strongly either way)?

**Comment by klauer** [comment]
@dchabot no valid reason, except for the Xspress3 IOC being a nightmare to work with. :) I definitely agree that it should live there. 

Not quite sure where to draw the line saying "you must do this in an IOC" or "this is okay on the Python level".

This example is definitely trivial. However, I think the benefit of having scipy/numpy/devices/etc at one's disposal in Signal value calculations would be of benefit to someone.

**Comment by tacaswell** [comment]
This also provides a way to do read-only pseudo axes.

This could also be super useful as a prototyping tool.  If someone has a 'great idea' for a new transformed PV you can hack it up in python in 10min and if it is actually useful push it down to an IOC and if not; you only spent 10min on it :smiling_imp:.

**Comment by danielballan** [comment]
Right. Refusing to implement something in Python on principle is like adopting an engineering control to solve a problem that calls for an administrative control.

**Comment by danielballan** [comment]
@dchabot Fair.

**Comment by klauer** [comment]
Fleshed this out a bit more, rebased, and added tests. Leaving it up to others to decide if it belongs or not.

**Pull request merged**
