### PR TITLE
ENH: Try to resolve errors due to HDF5 warmup automatically.

### PR DESCRIPTION
**Pull request by danielballan**
A quick attempt at resolving #598, dashed off during a conference.

@prjemian, do you have time to test this?

### CODE REVIEW

**Comment by tacaswell** [comment]
While practical, I am uncomfortable with this.  I don't think we understand the underlying problem well enough to say that in all cases if staging times out we should try exactly once to run the warmup and then try again.  Are we sure that if `stage` has failed `unstage` will not also fail?  If stage is what is crashing the IOC this just delays the final issue.  Are we sure that hdf5 is the only plugin with this problem?

I think it would be better to add a call to warmup to the `__init__` method (not sure if putting it in the hdf5 plugin or in the top-level AD devices is better) and if we get a timeout during stage re-raise with a clearer exception method (which is how I read @prjemian's comment in #598).

**Comment by tacaswell** [comment]
> Hmm. Not sure I like the idea that init would cause the detector to acquire though.

That was my compromise on not liking `stage` to acquire.  On board with warm-up being a fully explicit activity and this error message just telling the user they need to do it.

This may be a problem for long un-attended operation, but if this is becoming an issue then that means your AD IOC is restarting randomly which is probably a sign of a deeper problem.

Maybe raise a custom Exception sub-class so plans that _do_ want to auto-warmup can?

**Comment by prjemian** [comment]
Random ioc restarts?  Hardly the case.  We have a lot of IOCs.  People
reboot them by their choice.  We see this in fresh IOCs (after they
restart).  Also, sometimes they crash, needing a reboot.  People forget or
overlook this step, though.

We must be prepared to identify this.

**Comment by danielballan** [comment]
> We must be prepared to identify this.

Yep, this aligns with my feeling that biggest yet-unfulfilled potential for ophyd is more informative errors. But we should generally resist magically fixing things and thus masking deeper problems (as this PR of my does...).

**Comment by hhslepicka** [comment]
@teddyrendahl In any case you get the connection callback so you would be covered even in the edge case that you mentioned.

```python
In [1]: from epics import PV

In [2]: def conn_cb(conn, *args, **kwargs):
   ...:     print("Connection Changed to: ", conn)
   ...:

In [3]: def val_cb(value, *args, **kwargs):
   ...:     print("PV changed to: ", value)
   ...:

In [4]: pv = PV('MTEST:Float', connection_callback=conn_cb, callback=val_cb)

In [5]: Connection Changed to:  True
PV changed to:  0.0
```

**Pull request closed without merging**
