### PR TITLE
FIX: Allow for nested plugins in AreaDetector

### LINKED ISSUE #635: AreaDetector Does not Traverse Entire Tree
`AreaDetector` assumes that all plugins are the direct children of `ADBase`. This prevents grouping plugins like

```python
class CommonPlugins(Device):
        stats1 = Cpt(...)
        stats2 = Cpt(...)
         ....

class CommonDetector(ADBase):
      common_plugins = Cpt(CommonPlugins, ...)
```

https://github.com/NSLS-II/ophyd/blob/dd6a3a0335c7e9d6fe6fc0beb121977cfe637aa7/ophyd/areadetector/base.py#L188

### PR DESCRIPTION
**Pull request by teddyrendahl**
* Add a utility `devices_in_parent` to search through entire device lineage
* Make sure any references to `_sub_devices` are replaced with the `devices_in_parent`

Closes #635

### CODE REVIEW

**Comment by danielballan** [comment]
Should we wait on this and refactor in light of @klauer's "walk signals / walk components" work in #630?

**Comment by teddyrendahl** [comment]
Happy to wait and refactor to use the new utilities. Just wanted to put this up as it was on my mind.

**Comment by klauer** [comment]
There are 4 new utilities related to this:
1. `walk_components` (classmethod - give me all `Components` and `DynamicDeviceComponents`)
2. `walk_signals` (instancemethod - give me all `Signal`s)
3. `walk_subdevice_classes` (classmethod - give me all sub-[sub-]`Device` classes)
4. `walk_subdevices` (instancemethod - give me all sub-[sub-]`Device` instances)

I believe @teddyrendahl is looking for (4) in this case. We should discuss if people like/hate the implementations.

**Comment by klauer** [comment]
I have a rebased version of this on top of #674 which uses `walk_subdevices` and also addresses #687. I'll push once #674 is in.

**Comment by tacaswell** [comment]
I also fixed a related problem at https://github.com/NSLS-II-HXN/hxntools/commit/54bfd72e37d99ab63dae2067a0f876fad0c3967a this seems more general.

**Comment by klauer** [comment]
While I approve of this PR now, I'm also the one who modified @teddyrendahl's original. @tacaswell?

**Pull request merged**
