### PR TITLE
Fix version

### PR DESCRIPTION
**Pull request by jrmlhermitte**
fix the case where `epics.__version__` may not be a version string

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
issue happened here: https://github.com/NSLS-II/databroker/blob/master/doc/source/tutorial.rst

where the output was:
```
/home/julienl/research/projects/ophyd/ophyd/_pyepics_shim.py in get_pv_form(version)
   206
   207     print("version is {}".format(version))
--> 208     version = parse_version(_fix_git_versioning(version))
   209
   210     if version is None:

/home/julienl/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py in parse_version(v)
   209 def parse_version(v):
   210     try:
--> 211         return SetuptoolsVersion(v)
   212     except packaging.version.InvalidVersion:
   213         return SetuptoolsLegacyVersion(v)

/home/julienl/anaconda3/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/version.py in __init__(self, version)
   198     def __init__(self, version):
   199         # Validate the version and parse it into pieces
--> 200         match = self._regex.search(version)
   201         if not match:
   202             raise InvalidVersion("Invalid version: '{0}'".format(version))

TypeError: expected string or bytes-like object
```

The variable `epics.__version__` was:
`<MyMock object at 0x7f0d7f23d860>`

This should likely be fixed upstream, but probably good to handle here, as @danielballan 's suggestion

**Comment by tacaswell** [comment]
It is probably better to fix the Mock object that is getting passed in than to put the cut-out in ophyd.

**Comment by danielballan** [comment]
@tacaswell That sounds right, but a defensive cut-out here (and maybe a GH issue reminding us to remove it in a year) is good defense in depth -- aiming at old versions of pyepics.

**Comment by jrmlhermitte** [comment]
I like @tacaswell . Since the issue was fixed in bluesky [here](https://github.com/NSLS-II/databroker/pull/346), perhaps we can close this for now and re-open if we find another issue?

**Comment by danielballan** [comment]
Works for me. Feel like submitting your first pyepics PR and fixing this upstream?

**Pull request closed without merging**
