### PR TITLE
ENH: add config and ommitted components to SynAxis classes

### PR DESCRIPTION
**Pull request by tacaswell**
These don't relate to the delay function of the axis at all but
are useful to exercise all the kinds.

### CODE REVIEW

**Comment by awalter-bnl** [comment]
Can we also add a 'settle_time' component? This is required for the time estimation?

**Comment by tacaswell** [comment]
real motors do not have settle_time as a component either, it looks like it is a property on `PositionerBase`.  We should probably clean that inconsistency up first.

**Comment by awalter-bnl** [comment]
OK, so if we don't think it is necessary to ever add a 'settle_time' to a motor movement I can remove that from the time estimate. It is true that the same outcome can be done by using 'fixed_mode' on the detector and then setting acquisition_period = acquisition_time + settle_time.

**Comment by tacaswell** [comment]
Sorry, what I meant is that we need to sort out a way to promote 'settle_time' to be a component on `PositionerBase` (rather than a property) to support the time estimation.  We should get this fixed on the 'mainline' part of the codebase before we add it to the simulators.

**Comment by teddyrendahl** [comment]
This makes nicer Typhon screens!

**Comment by tacaswell** [comment]
@teddyrendahl that may or may not be what motivated me to add these....

**Pull request merged**
